_BASE_: "../Base-RCNN-FPN-D2SA.yaml"
MODEL:
  MASK_ON: True     
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
    USE_BOUNDARY: True
    USE_VISIBLE : True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    NAME: "DBAM"
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'final-D2SA'